# Generated by Django 5.1.2 on 2024-10-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='payment_details',
            field=models.TextField(blank=True, verbose_name='Реквизиты для оплаты заказа'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='receiving_address',
            field=models.TextField(blank=True, verbose_name='Адрес самовывоза'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='F:\\__Development\\botMatherAline\\tgbot\\media', verbose_name='Фото организации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='F:\\__Development\\botMatherAline\\tgbot\\media', verbose_name='Фото товара'),
        ),
    ]
