# Generated by Django 5.1.2 on 2024-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiving',
            field=models.CharField(choices=[('receiving_point', 'Самовывоз'), ('delivery', 'Доставка')], default='receiving_point', max_length=30, verbose_name='Способ получения'),
        ),
    ]
